project 'xtrack_mobile.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
 require_relative '../node_modules/react-native/scripts/react_native_pods'
 require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'xtrack_mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  # Pods for xtrack_mobile
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

end
